#
# Copyright (C) 2007 Arnold Krille
# Copyright (C) 2007 Pieter Palmers
#
# This file originates from FFADO (www.ffado.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
from string import Template

Import( 'env' )

# paths where include files can be found
env.AppendUnique( CPPPATH=["#/", "#/common", "#/common/jack", "#/macosx"] )

#
# Define the source files
#

srcfiles_macosx_server = ['#/common/Jackdmp.cpp']

srcfiles_macosx_coreaudio = ['JackCoreAudioDriver.cpp']

srcfiles_macosx_dummy = ['#/common/JackDummyDriver.cpp']

#
# Start building
#

# build the server and its backends
serverenv = env.Copy()
serverenv.PrependUnique( LIBPATH=env['build_base'] )
serverenv.PrependUnique( LIBS=["jackdmp", "dl"] )

server = serverenv.Program("jackdmp", srcfiles_macosx_server)
serverenv.Install( env['bindir'], server )

drv = serverenv.SharedLibrary( "jack_dummy", srcfiles_macosx_dummy )
serverenv.InstallAs( env['libdir']+ "/jackmp/jack_dummy.so", drv )

drv = serverenv.SharedLibrary( "jack_coreaudio", srcfiles_macosx_coreaudio )
serverenv.InstallAs( env['libdir']+ "/jackmp/jack_coreaudio.so", drv )
