#! /usr/bin/python3
# encoding: utf-8


def build(bld):
    bld.exec_command('cd man ; sh fill_template {} {}'.format(
        bld.env['JACK_VERSION'],
        bld.env['BUILD_JACK_EXAMPLE_TOOLS'])
    )
    bld.install_files(bld.env['MANDIR'], bld.path.ant_glob('*.1'))
