#
# Copyright (C) 2007 Arnold Krille
# Copyright (C) 2007 Pieter Palmers
# Copyright (C) 2008 Marc-Olivier Barre
#
# This file originates from FFADO (www.ffado.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
from string import Template

Import('env')

# Paths where include files can be found
env.AppendUnique(CPPPATH=['#/', '#/common'])

#
# Source files section
#

test_programs = {
    'synchroClient': [
        'testSynchroClient.cpp'
        ],
    'synchroServer': [
        'testSynchroServer.cpp'
        ],
    'synchroServerClient': [
        'testSynchroServerClient.cpp'
         ],
    'testSem': [
        'testSem.cpp'
        ],
    'jack_test': [
        'jack_test.cpp'
        ],
}

# Libraries to link
extra_libs = {}
for test_program in test_programs:
    extra_libs[test_program] = ['jackserver']

#
# Build section
#

# build the tests
testenv = env.Copy()
testenv.PrependUnique(LIBPATH=env['build_base'])
testenv.PrependUnique(LIBS=env['CLIENTLIB'])

for test_program, test_program_source in test_programs.items():
    testenv.Program(test_program, test_program_source)
